# logging.level.root=DEBUG
defaultCategory: test

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/todo.db
    username: sa
    password: sa
    initialization-mode: always

  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop

  h2:
    console:
      enabled: true

#  security:
#    user:
#      name: "jens"
#      password: "123"

management:
  endpoints:
    web:
      exposure:
        include: "env,health,shutdown,beans,info,metrics,loggers"
  endpoint:
    shutdown:
      enabled: true
